import * as THREE from "three";
import { EventInfo, InputManager } from "../../core/input/InputManager";
import { BaseMeasureDrawable } from "../../core/measure/BaseMeasureDrawable";
import { MeasurementData, MeasurementType } from "../../core/measure/BaseMeasurement";
import type { BaseViewer } from "../../core/viewers";
export declare class MeasurementManager {
    scene: THREE.Scene;
    selectedMeasurementDrawable: BaseMeasureDrawable | undefined;
    private overlayRender?;
    private drawableList;
    private drawableHelperList;
    private viewer;
    private inputManager;
    private osnapHelper;
    private measurements;
    private activeMeasurementType;
    private undoRedoHelper;
    private mobileTouchHelper?;
    constructor(viewer: BaseViewer, input: InputManager);
    private initEvents;
    get canvas(): HTMLCanvasElement;
    get raycaster(): THREE.Raycaster | undefined;
    getPixelSizeInWorldCoord(): number;
    addMeasurement(drawable: BaseMeasureDrawable, needRecord?: boolean): void;
    createMeasurement(data: MeasurementData): import("../../core/canvas").Drawable;
    removeMeasurement(drawable: BaseMeasureDrawable, needRecord?: boolean): void;
    updateSnapTolerance(pixelSize?: number): void;
    activateMeasurement(type: MeasurementType): void;
    deactivateMeasurement(): void;
    getActiveMeasurementType(): MeasurementType | undefined;
    isMeasurementActive(): boolean;
    isMeasurementMeasuring(): boolean;
    getMeasurementsData(): MeasurementData[];
    setMeasurementsData(dataArray: MeasurementData[]): void;
    setMeasurementVisibility(id: string, visible: boolean): boolean;
    setMeasurementsVisibility(visible: boolean): void;
    clearMeasurements(): void;
    removeMeasurementById(id: string, needRecord?: boolean): void;
    selectMeasurementById(id: string): void;
    selectMeasurement(drawable: BaseMeasureDrawable): void;
    unselectMeasurement(): void;
    undo(): void;
    redo(): void;
    clearUndoRedo(): void;
    destroy(): void;
    keydown: (e: EventInfo) => void;
}
