import { BasePlaneSection } from "./BasePlaneSection";
import { BimViewer } from "../viewers/BimViewer";
import { OrthographicCamera, PerspectiveCamera, Raycaster, Scene, WebGLRenderer } from "three";
import { OrbitControls } from "three/examples/jsm/controls/OrbitControls";
import { PickSectionPopPanel } from "../../components/pop-panel/PickSectionPopPanel";
import { Tooltip } from "../../components/tool-tip/Tooltip";
export declare class PickPlaneSection {
    private readonly container?;
    protected bimViewer: BimViewer;
    protected camera: PerspectiveCamera | OrthographicCamera;
    protected controls: OrbitControls;
    protected scene: Scene;
    protected renderer: WebGLRenderer;
    protected objectUuids: string[];
    isShowSectionPlane: boolean;
    protected sectionPlane?: BasePlaneSection;
    protected popPanel?: PickSectionPopPanel;
    protected tooltip?: Tooltip;
    protected isSelected: boolean;
    protected raycaster: Raycaster;
    constructor(bimViewer: BimViewer, objectUuids: string[], container?: HTMLElement | undefined);
    protected updateMouseAndRay(event: MouseEvent): void;
    protected pickFace(evt: MouseEvent): boolean;
    init(): void;
    protected clickOnceListerner: (event: MouseEvent) => void;
    open(): void;
    close(): void;
    enableSection(): void;
    cancelSection(): void;
    hideSectionPlane(): void;
    showSectionPlane(): void;
}
